source "http://rubygems.org"
#source "http://ruby.taobao.org"

gem "rake"
gem "rspec"
gem "cfoundry", "= 0.4.16"
gem "vcap_logging", ">= 1.0"
gem "interact"
gem "curb"
gem "mongo"
gem "bson_ext"
gem "yajl-ruby"
gem "nokogiri"
gem "fuubar"
gem "progressbar", "~> 0.11.0"
gem "rest-client"
gem "console-vmc-plugin"

gem "caldecott"
gem "rspec_parallel", ">= 0.1.6"
