source "http://rubygems.org"

gem "rake"
gem "rspec"
gem "cfoundry", ">= 0.1.1"
gem "vcap_logging", ">= 1.0"
gem "interact"
gem "curb"
gem "mongo"
gem "bson_ext"
gem "yajl-ruby"
gem "nokogiri"
gem "parallel_tests"
